#Trial is over............? 
# apiVersion: "datadoghq.com/v2alpha1"
# kind: "DatadogAgent"
# metadata:
#   name: "datadog"
#   namespace: datadog
# spec:
#   global:
#     credentials:
#       apiSecret:
#         secretName: "datadog-secret"
#         keyName: "api-key"
#     clusterName: "kodiak-cluster"
#   logs:
#     enabled: true
#     containerCollectAll: true
#     containerRuntime: "containerd"
#   apm:
#     enabled: true
#     portEnabled: true
#   kubeStateMetricsCore:
#     enabled: true
